---
apiVersion: v1
kind: Namespace
metadata:
  name: hyper-config-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-development
  namespace: hyper-config-a
  labels:
    app: nginx
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      environment: development
  template:
    metadata:
      labels:
        app: nginx
        environment: development
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hyper-config-a
spec:
  selector:
    app: nginx
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
